name: Quebec City Ideas
favicon: null
layout_spectrum: 0.74486
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcdce4'
    - '#fefefe'
    - '#c96a30'
    - '#db9100'
    - '#8f3906'
  brandStrength: 0.0625
  lightness: 0.3125
  saturation: 0.6889299172908068
  rhythmicContrast: 0.5
purpose: []
